trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'DockerBuildAndPush'
    displayName: "Build and Push Docker Image"
    jobs: 
      - job: 'Docker_Build_Push'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'dockerreg'
              repository: 'pythonrepo'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'
