trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'DockerBuild'
    displayName: "Building Docker Image"
    jobs: 
      - job: 'Docker_Build'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-svc'
              repository: 'pythonapprepo'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'

  - stage: 'DockerPush'
    displayName: 'Pushing docker image to ACR'
    jobs:
      - job: 'Docker_Push'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-svc'
              repository: 'pythonapprepo'
              command: 'push'
              tags: 'latest'
  - stage: 'PublishArtifacts'
    displayName: 'Publish Build Artifacts'
    jobs:
      - job: 'Publish_Artifacts'
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'